### ISSUE TITLE
Bug: 好像不能使用了

### ISSUE THREAD

**Issue by Mirakelor** [OpportunityLiu/LrcExt.Aurora.Music#3]
任何歌都显示无歌词

**Comment by OpportunityLiu** [comment]
毕竟是别人的接口，能用只是巧合

**Comment by Mirakelor** [comment]
能麻烦您把网易云歌词的接口换成我自己搭的” https://panic.fuckc.cf/lyric?id= “吗，这个插件很好用真的不想弃用，我保证这个接口会持续运行的，谢谢您。
